# bind the user 'michele' to the role of node developer
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: michelle-node-dev-binding
subjects:
- kind: User
  name: michelle
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: node-developer
  apiGroup: rbac.authorization.k8s.io