apiVersion: v1
kind: Pod
metadata:
  name: event-simulator
spec:
  containers:
  - name: event-simulator
    image: kodekloud/event-simulator
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"