apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTFvdmhucXNubjFFRSs3UU1LNm11R3hJZHIyMDUvdm9QQ2ZxcktkK3VTNUR3CnY5WFVadGdwNzAzMGYvNlhvbHJNamRxNUFzcWpaRllpMGgwS0ZSN2hHVUdhR3RKbnJ1Z2IzOFQzc0xHT3JRM0wKTHIwQ2Rvc2s5cmhDODFVZTZ1ZmJiUFRJSFFTUWtycWlxZkpHVXc4MVQzWWhjS3RTWEprTEdFK1BQRmVYRGZrSgpKUlhzUlNaK05DbzRTcFd2djVHam5zaGN6NWtBM3dCckowNWRqT3VjQUZLcWZ1SlFwc28xT1c4RUlBcEZMRXkyCjQwS1pObXNqSlpCK3lNcXNSMFZGTy81UUgxWDhhVjdicTNmTG5Ub01ZVDdBSWtSZHlOTDh1K2o3TlNKUzdYV1UKNTVKU0p2VHpSQ3VjRUY4YTBMSTRYUkRYbzNuRUMxREV6MjdnVEJXQlZ3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBTS9naGRaTXhTSTE1bmJZL3Q4Z28yeFhUSlhQVkJaSEFzc1FXVXY2RXZTdHpCSElSSTRVCi9VYXMvK21FVVYzcEVnYit3QWNnRzRmd1N2UlpDaHlqZ3BvMUJYYlFHb1BzUXdDUTI2Tzh0Qk84TTlsSDNBZjIKMWlOS3JrclZUTDJ2T3FVMDRCWFJxbTQzRElTMWJpTXo1UGJJQ2gvemo4R3huTnFZZEcrK3dVSnhYLzVQYzFYRgphZU53N3lTeTlpeEVmTE5LZVFkT1VTNDhwY0hLNExvVDIrQ1VnMnAvaGNndGwyeGFTS29ReDQ2cENpSG5nWnZRClhlakgwSWVpdE1jU1dCNURFQmVDbEVIek4zOEtEZHdReEd2bDNpWEl1M0c3b1c5NjN3T0tlVFg0NzZyVkFIYmsKeS9hSG4rSGdWOGprNVl2bUY0Sm1sSVRzV091ckZmTlFkSG89Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth