apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
    
spec:
  # template 
  template: 
    # the pod definition (identical content to a pod definition yaml)
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end

    spec:
      containers:
        - name: nginx-container
          image: nginx

  # number of replicas of the pod definition
  replicas: 3
